#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef KOCHAVAENTITLEMENTS_SWIFT_H
#define KOCHAVAENTITLEMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KochavaEntitlements",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@protocol KVAEntitlementsReceiptReporter;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements38KVAEntitlementsReceiptReporterProvider_")
@protocol KVAEntitlementsReceiptReporterProvider
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end

@class NSString;
@class KVAContext;
@class KVAEntitlementsConfig;
@class KVAEntitlementsGeneral;
@class KVANetworking;
@class KVAEntitlementsReporting;

/// The class KVAEntitlements provides an interface between a host application and Kochava’s Entitlements servers.
SWIFT_CLASS_NAMED("KVAEntitlements")
@interface KVAEntitlements : NSObject <KVAEntitlementsReceiptReporterProvider>
/// A shared instance, for convenience.
/// This is the preferred way of using an entitlements instance.  To complete the integration you must call func <code>registerIdentity(withNameString:valueString:)</code> followed by func <code>start()</code>.  You may alternatively use a constructor to create your own entitlements.  The shared instance simplifies your implementation as you do not need to store an entitlements instance somewhere in a public location in your own code.
/// By default this instance will use the default storage location equivalent to calling <code>init(storageIdString:)</code> with storageIdString nil.  If you wish to specify an alternative storage location, see var <code>sharedStorageIdString</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nonnull shared;)
+ (KVAEntitlements * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// A shared instance, for convenience— optional.
/// See var <code>shared</code>.  This variable will be nil prior to the shared instance being defaulted.  This may be used to optionally invalidate any existing shared instance without causing it to first be defaulted in the process.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nullable shared_optional;)
+ (KVAEntitlements * _Nullable)shared_optional SWIFT_WARN_UNUSED_RESULT;
/// The shared instance, an ambiguated form of the var <code>shared</code> which conforms to protocol KVASharedPropertyProvider.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id _Nonnull sharedInstance;)
+ (id _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements()
/// }
///
/// \endcode
- (nonnull instancetype)init;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements(storageIdString: "alternate")
/// }
///
/// \endcode\param storageIdString An optional storage identifier.  The storage identifier should be left unset (nil) unless you have a reason to not use the default storage space.  See default constructor KVAEntitlements().
///
- (nonnull instancetype)initWithStorageIdString:(NSString * _Nullable)storageIdString OBJC_DESIGNATED_INITIALIZER;
/// Configure the instance with an object.
/// This is the same method which is used to configure the instance when the <code>config</code> response is returned from Kochava’s servers.  It can also be called from the host to change the defaults of various parameters (or else override them).  The structure of the object you provide has the same capability as that which the server may return.  Additionally you can wrap the parameters you provide in special objects with special keys <code>$default$</code>, <code>$default.append$</code>, <code>$override$</code>, or <code>$override.append$</code>, to indicate how these options are treated relative to the server’s options.
/// | Special Key | Treatment  |
/// — | —
/// $default$ |  Elements within this object will serve as a default for any options of the same name when not specified by the server.  The use of this option will replace any previous use of <code>$default$</code> or <code>$default.append$</code>.
/// $default.append$ |  Elements within this object will append to any previously established <code>$default$</code>.  You may use this without using <code>$default$</code> first, allowing you to specify multiple defaults over the course of multiple configuration calls.  The use of this option is generally considered preferred relative to the others.  That is because as a default it still allows for the server to specify overrides, and as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// $override$ |  Elements within this object will override any options of the same name specified by the server.  Use this option when you do not want to allow the server to specify overrides.  The use of this option will replace any previous use of <code>$override$</code> or <code>$override.append$</code>.
/// $override.append$ |  Elements within this object will append to any previously established <code>$override$</code>.  You may use this without using <code>$override$</code> first, allowing you to specify multiple overrides over the course of multiple configuration calls.  The use of this option is generally preferred to <code>$override$</code>.  That is because as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// The following example will deny the collection of two datapoints, the idfa and idfv.  Ordinarily the best way to do this is through the Kochava dashboard, where these can be controlled within multiple version(s) of an app already in production.  However, if at build time you wanted to explicitly override server-side control, such that these two items effectively always appear in the deny datapoints list, the following code would do so:
/// <h2>Example</h2>
/// \code
/// // entitlementsConfigureObject
/// let entitlementsConfigureObject =
/// [
///     "$override.append$":
///     [
///         "privacy":
///         [
///             "deny_datapoints":
///             [
///                 "idfa",
///                 "idfv"
///             ]
///         ]
///     ]
/// ]
///
/// // KVAEntitlements
/// KVAEntitlements.shared.configure(with: entitlementsConfigureObject, context: .host)
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
/// KVAEntitlements.shared.start()
///
/// \endcode\param object An object from which to configure the instance.  This is most commonly a JSON object.
///
/// \param context The context from which the object was provided.  In rare cases this may have some bearing on the proper interpretation of what was provided.
///
- (void)configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Configure the instance with an object.
/// This function is equivalent to func configure(with:context) however this does not first dispatch to the globalSerial queue.  It is the protocol conformance of KVAConfigureWithProtocol.  You should not use this function directly unless you have a specific need to not perform the preferred dispatch.
- (void)kva_configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
/// Start the entitlements instance.
/// An identity must be registered prior to making this call.  To do this, instead see func <code>registerIdentity(withNameString:valueString:)</code>.  This method is called by those two methods, and provides public conformance to protocol KVAStartable.  This method can be used to start an instance of a entitlements which was created from decoded JSON.
- (void)start;
/// Return a description of the instance.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Invalidate the instance.
/// When using this method with the shared instance, you are guaranteed to be re-defaulted a new instance the next time it is referenced, and you may immediately move forward to re-configure and start it.
- (void)invalidate;
/// Invalidate the instance.
/// See func <code>invalidate()</code>
- (void)invalidateWithAsyncBool:(BOOL)asyncBool printLogMessageBool:(BOOL)printLogMessageBool;
/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
@property (nonatomic, readonly, strong) KVAEntitlementsConfig * _Nonnull config;
/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
@property (nonatomic, readonly, strong) KVAEntitlementsGeneral * _Nonnull general;
/// A feature which provides networking support.
/// The networking instance manages the exchange of data between the client and various server(s), along with the associated tasks, network transactions, adapters, and instructions.  See class KVANetworking in module KochavaCore.
@property (nonatomic, readonly, strong) KVANetworking * _Nonnull networking;
/// A feature which is responsible for the collection of datapoints.
@property (nonatomic, readonly, strong) KVAEntitlementsReporting * _Nonnull reporting;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
/// A string used as a  storage identifier for the shared instance.
/// This is used to further qualify where in persistent storage the information for this instance is stored.  This property should not be used except in very specific circumstances.  Please contact your client success representative if you are interested in using this.  You would set this value to a short unique string consisting of regular alphanumeric characters.
/// Following deployment with a given storage identifer this should never be changed except to represent an entirely new integration.
/// If used, it is imperative that this value be consistently set prior to accessing the shared instance for the first time.  You must make accommodations to set this as early as possible, where it would be prior to any access to var <code>shared</code> throughout all of your code.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable sharedStorageIdString;)
+ (NSString * _Nullable)sharedStorageIdString SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedStorageIdString:(NSString * _Nullable)sharedStorageIdString;
/// A boolean indicating whether or not the instance has been started.
@property (nonatomic, readonly) BOOL startedBool;
@end


/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
/// This feature interfaces with Kochava’s servers to provide a server-based configuration.
SWIFT_CLASS_NAMED("KVAEntitlementsConfig")
@interface KVAEntitlementsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which is responsible for the collection of datapoints.
/// <h1>Thread Safety</h1>
/// The underlying APIs being used to collect datapoints fall under various classifications of thread safety.  If an API is not thread safe then it must be collected on the main thread, otherwise it may be collected on the caller’s thread.  Anything which must be collected on the main thread must be viewed as asynchronous, along with those APIs which are themselves inherently asynchronous;  however, all other APIs may be viewed as synchronous.  In every case these thread safety classifications apply to the internal implementation stategies of the associated adapters, but the adapters themselves exist in part to create wrappers which have their own API(s) which are themselves uniform and universally thread safe.
/// Apple’s documentation on thread safety can be found here:
/// https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html
/// <h2>Internal Implementation Strategy Classifications</h2>
/// | Class | Safe | Notes |
/// — | — | —
/// Bundle | Yes | Apple’s documentation classifies Bundle under “Thread-Safe Classes and Functions”.
/// Locale | Yes* | Locale thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing is taken to be thread safe.
/// ProcessInfo | Yes | ProcessInfo is said to be thread-safe as of macOS 10.7 and later.
/// UIDevice | Yes* | UIDevice thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing may be thread safe.  However, Apple’s docs also say, “For the most part, UIKit classes should be used only from an application’s main thread. This is particularly true for classes derived from UIResponder or that involve manipulating your application’s user interface in any way.”  UIDevice is part of UIKit, however it is not derived from UIResponder (but rather NSObject).  This method is taken to not be involved in manipulating the application’s user interface.   https://developer.apple.com/documentation/uikit
/// Special | Varies | This classification is used for special cases.  There should be additional documentation in reference(s) which talk about the case.
/// <em>Yes*</em> - Items with this designation are taken to be safe.  They lack some level of documentation and/or clarity where thread safety is concerned, but often generally have a track record of being safe.
SWIFT_CLASS_NAMED("KVAEntitlementsDatapoints")
@interface KVAEntitlementsDatapoints : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
SWIFT_CLASS_NAMED("KVAEntitlementsGeneral")
@interface KVAEntitlementsGeneral : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
@end


/// A feature which is responsible for entitlements-specific logging activities.
/// You can set the KVALog.shared.level to control what level of log messages are printed, as well as configure various other options through module KochavaCore class KVALog.
SWIFT_CLASS_NAMED("KVAEntitlementsLogging")
@interface KVAEntitlementsLogging : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAProduct;

/// A class which defines the entitlements product.
/// A product in this context generally refers to the result of a build.
/// note:
/// This is currently overridden to be a subclass of NSObject rather than KVAProduct so that it can be represented in Objective-C.  If you use KVAProduct it will still build, but the automatic module registration will fail to locate the class.  You can see early evidence of the problem if you also make the shared property be of the class type, where the compiler will say that it cannot use @objc because it cannot be expressed in Objective-C.  This is apparently a problem that Swift has providing Objective-C compatibility to Swift classes which subclass other Swift classes across modules.  For example, KVACoreProduct does not have this problem, presumably because it’s in the same module as KVAProduct.  In order to convert this class to subclass KVAProduct, or to subsequently allow shared to be of the class’ type, a means of registering/loading the class as a Swift-only class would be required.  More importantly, however, we’d need to give up public Objective-C support.  Since that doesn’t seem possible, the only alternative would be that Apple fixes this issue and provides the necessary support, assuming that’s possible.
SWIFT_CLASS_NAMED("KVAEntitlementsProduct")
@interface KVAEntitlementsProduct : NSObject
/// The singleton shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAProduct * _Nonnull shared;)
+ (KVAProduct * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Defines the parameters for the tracker product.
SWIFT_CLASS("_TtC19KochavaEntitlements28KVAEntitlementsProductParams")
@interface KVAEntitlementsProductParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAReceipt;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements30KVAEntitlementsReceiptReporter_")
@protocol KVAEntitlementsReceiptReporter
/// Reports a receipt.
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@end



/// A controller for working with entitlements receipts.
SWIFT_CLASS_NAMED("KVAEntitlementsReporting")
@interface KVAEntitlementsReporting : NSObject <KVAEntitlementsReceiptReporter, KVAEntitlementsReceiptReporterProvider>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end


/// A feature which provides for the internal observation of sessions.
SWIFT_CLASS_NAMED("KVAEntitlementsSessions")
@interface KVAEntitlementsSessions : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;
@class NSData;

/// An App Store receipt.
SWIFT_CLASS_NAMED("KVAReceipt")
@interface KVAReceipt : NSObject
/// A method which reports the current receipt.
+ (void)report;
/// A method which reports a receipt, along with an associated transaction’s details.
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithPriceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
/// \param reporter An instance which conforms to protocol KVAEntitlementsReceiptReporterProvider.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString reporter:(id <KVAEntitlementsReceiptReporterProvider> _Nullable)reporter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef KOCHAVAENTITLEMENTS_SWIFT_H
#define KOCHAVAENTITLEMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KochavaEntitlements",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@protocol KVAEntitlementsReceiptReporter;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements38KVAEntitlementsReceiptReporterProvider_")
@protocol KVAEntitlementsReceiptReporterProvider
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end

@class NSString;
@class KVAContext;
@class KVAEntitlementsConfig;
@class KVAEntitlementsGeneral;
@class KVANetworking;
@class KVAEntitlementsReporting;

/// The class KVAEntitlements provides an interface between a host application and Kochava’s Entitlements servers.
SWIFT_CLASS_NAMED("KVAEntitlements")
@interface KVAEntitlements : NSObject <KVAEntitlementsReceiptReporterProvider>
/// A shared instance, for convenience.
/// This is the preferred way of using an entitlements instance.  To complete the integration you must call func <code>registerIdentity(withNameString:valueString:)</code> followed by func <code>start()</code>.  You may alternatively use a constructor to create your own entitlements.  The shared instance simplifies your implementation as you do not need to store an entitlements instance somewhere in a public location in your own code.
/// By default this instance will use the default storage location equivalent to calling <code>init(storageIdString:)</code> with storageIdString nil.  If you wish to specify an alternative storage location, see var <code>sharedStorageIdString</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nonnull shared;)
+ (KVAEntitlements * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// A shared instance, for convenience— optional.
/// See var <code>shared</code>.  This variable will be nil prior to the shared instance being defaulted.  This may be used to optionally invalidate any existing shared instance without causing it to first be defaulted in the process.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nullable shared_optional;)
+ (KVAEntitlements * _Nullable)shared_optional SWIFT_WARN_UNUSED_RESULT;
/// The shared instance, an ambiguated form of the var <code>shared</code> which conforms to protocol KVASharedPropertyProvider.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id _Nonnull sharedInstance;)
+ (id _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements()
/// }
///
/// \endcode
- (nonnull instancetype)init;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements(storageIdString: "alternate")
/// }
///
/// \endcode\param storageIdString An optional storage identifier.  The storage identifier should be left unset (nil) unless you have a reason to not use the default storage space.  See default constructor KVAEntitlements().
///
- (nonnull instancetype)initWithStorageIdString:(NSString * _Nullable)storageIdString OBJC_DESIGNATED_INITIALIZER;
/// Configure the instance with an object.
/// This is the same method which is used to configure the instance when the <code>config</code> response is returned from Kochava’s servers.  It can also be called from the host to change the defaults of various parameters (or else override them).  The structure of the object you provide has the same capability as that which the server may return.  Additionally you can wrap the parameters you provide in special objects with special keys <code>$default$</code>, <code>$default.append$</code>, <code>$override$</code>, or <code>$override.append$</code>, to indicate how these options are treated relative to the server’s options.
/// | Special Key | Treatment  |
/// — | —
/// $default$ |  Elements within this object will serve as a default for any options of the same name when not specified by the server.  The use of this option will replace any previous use of <code>$default$</code> or <code>$default.append$</code>.
/// $default.append$ |  Elements within this object will append to any previously established <code>$default$</code>.  You may use this without using <code>$default$</code> first, allowing you to specify multiple defaults over the course of multiple configuration calls.  The use of this option is generally considered preferred relative to the others.  That is because as a default it still allows for the server to specify overrides, and as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// $override$ |  Elements within this object will override any options of the same name specified by the server.  Use this option when you do not want to allow the server to specify overrides.  The use of this option will replace any previous use of <code>$override$</code> or <code>$override.append$</code>.
/// $override.append$ |  Elements within this object will append to any previously established <code>$override$</code>.  You may use this without using <code>$override$</code> first, allowing you to specify multiple overrides over the course of multiple configuration calls.  The use of this option is generally preferred to <code>$override$</code>.  That is because as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// The following example will deny the collection of two datapoints, the idfa and idfv.  Ordinarily the best way to do this is through the Kochava dashboard, where these can be controlled within multiple version(s) of an app already in production.  However, if at build time you wanted to explicitly override server-side control, such that these two items effectively always appear in the deny datapoints list, the following code would do so:
/// <h2>Example</h2>
/// \code
/// // entitlementsConfigureObject
/// let entitlementsConfigureObject =
/// [
///     "$override.append$":
///     [
///         "privacy":
///         [
///             "deny_datapoints":
///             [
///                 "idfa",
///                 "idfv"
///             ]
///         ]
///     ]
/// ]
///
/// // KVAEntitlements
/// KVAEntitlements.shared.configure(with: entitlementsConfigureObject, context: .host)
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
/// KVAEntitlements.shared.start()
///
/// \endcode\param object An object from which to configure the instance.  This is most commonly a JSON object.
///
/// \param context The context from which the object was provided.  In rare cases this may have some bearing on the proper interpretation of what was provided.
///
- (void)configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Configure the instance with an object.
/// This function is equivalent to func configure(with:context) however this does not first dispatch to the globalSerial queue.  It is the protocol conformance of KVAConfigureWithProtocol.  You should not use this function directly unless you have a specific need to not perform the preferred dispatch.
- (void)kva_configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
/// Start the entitlements instance.
/// An identity must be registered prior to making this call.  To do this, instead see func <code>registerIdentity(withNameString:valueString:)</code>.  This method is called by those two methods, and provides public conformance to protocol KVAStartable.  This method can be used to start an instance of a entitlements which was created from decoded JSON.
- (void)start;
/// Return a description of the instance.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Invalidate the instance.
/// When using this method with the shared instance, you are guaranteed to be re-defaulted a new instance the next time it is referenced, and you may immediately move forward to re-configure and start it.
- (void)invalidate;
/// Invalidate the instance.
/// See func <code>invalidate()</code>
- (void)invalidateWithAsyncBool:(BOOL)asyncBool printLogMessageBool:(BOOL)printLogMessageBool;
/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
@property (nonatomic, readonly, strong) KVAEntitlementsConfig * _Nonnull config;
/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
@property (nonatomic, readonly, strong) KVAEntitlementsGeneral * _Nonnull general;
/// A feature which provides networking support.
/// The networking instance manages the exchange of data between the client and various server(s), along with the associated tasks, network transactions, adapters, and instructions.  See class KVANetworking in module KochavaCore.
@property (nonatomic, readonly, strong) KVANetworking * _Nonnull networking;
/// A feature which is responsible for the collection of datapoints.
@property (nonatomic, readonly, strong) KVAEntitlementsReporting * _Nonnull reporting;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
/// A string used as a  storage identifier for the shared instance.
/// This is used to further qualify where in persistent storage the information for this instance is stored.  This property should not be used except in very specific circumstances.  Please contact your client success representative if you are interested in using this.  You would set this value to a short unique string consisting of regular alphanumeric characters.
/// Following deployment with a given storage identifer this should never be changed except to represent an entirely new integration.
/// If used, it is imperative that this value be consistently set prior to accessing the shared instance for the first time.  You must make accommodations to set this as early as possible, where it would be prior to any access to var <code>shared</code> throughout all of your code.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable sharedStorageIdString;)
+ (NSString * _Nullable)sharedStorageIdString SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedStorageIdString:(NSString * _Nullable)sharedStorageIdString;
/// A boolean indicating whether or not the instance has been started.
@property (nonatomic, readonly) BOOL startedBool;
@end


/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
/// This feature interfaces with Kochava’s servers to provide a server-based configuration.
SWIFT_CLASS_NAMED("KVAEntitlementsConfig")
@interface KVAEntitlementsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which is responsible for the collection of datapoints.
/// <h1>Thread Safety</h1>
/// The underlying APIs being used to collect datapoints fall under various classifications of thread safety.  If an API is not thread safe then it must be collected on the main thread, otherwise it may be collected on the caller’s thread.  Anything which must be collected on the main thread must be viewed as asynchronous, along with those APIs which are themselves inherently asynchronous;  however, all other APIs may be viewed as synchronous.  In every case these thread safety classifications apply to the internal implementation stategies of the associated adapters, but the adapters themselves exist in part to create wrappers which have their own API(s) which are themselves uniform and universally thread safe.
/// Apple’s documentation on thread safety can be found here:
/// https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html
/// <h2>Internal Implementation Strategy Classifications</h2>
/// | Class | Safe | Notes |
/// — | — | —
/// Bundle | Yes | Apple’s documentation classifies Bundle under “Thread-Safe Classes and Functions”.
/// Locale | Yes* | Locale thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing is taken to be thread safe.
/// ProcessInfo | Yes | ProcessInfo is said to be thread-safe as of macOS 10.7 and later.
/// UIDevice | Yes* | UIDevice thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing may be thread safe.  However, Apple’s docs also say, “For the most part, UIKit classes should be used only from an application’s main thread. This is particularly true for classes derived from UIResponder or that involve manipulating your application’s user interface in any way.”  UIDevice is part of UIKit, however it is not derived from UIResponder (but rather NSObject).  This method is taken to not be involved in manipulating the application’s user interface.   https://developer.apple.com/documentation/uikit
/// Special | Varies | This classification is used for special cases.  There should be additional documentation in reference(s) which talk about the case.
/// <em>Yes*</em> - Items with this designation are taken to be safe.  They lack some level of documentation and/or clarity where thread safety is concerned, but often generally have a track record of being safe.
SWIFT_CLASS_NAMED("KVAEntitlementsDatapoints")
@interface KVAEntitlementsDatapoints : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
SWIFT_CLASS_NAMED("KVAEntitlementsGeneral")
@interface KVAEntitlementsGeneral : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
@end


/// A feature which is responsible for entitlements-specific logging activities.
/// You can set the KVALog.shared.level to control what level of log messages are printed, as well as configure various other options through module KochavaCore class KVALog.
SWIFT_CLASS_NAMED("KVAEntitlementsLogging")
@interface KVAEntitlementsLogging : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAProduct;

/// A class which defines the entitlements product.
/// A product in this context generally refers to the result of a build.
/// note:
/// This is currently overridden to be a subclass of NSObject rather than KVAProduct so that it can be represented in Objective-C.  If you use KVAProduct it will still build, but the automatic module registration will fail to locate the class.  You can see early evidence of the problem if you also make the shared property be of the class type, where the compiler will say that it cannot use @objc because it cannot be expressed in Objective-C.  This is apparently a problem that Swift has providing Objective-C compatibility to Swift classes which subclass other Swift classes across modules.  For example, KVACoreProduct does not have this problem, presumably because it’s in the same module as KVAProduct.  In order to convert this class to subclass KVAProduct, or to subsequently allow shared to be of the class’ type, a means of registering/loading the class as a Swift-only class would be required.  More importantly, however, we’d need to give up public Objective-C support.  Since that doesn’t seem possible, the only alternative would be that Apple fixes this issue and provides the necessary support, assuming that’s possible.
SWIFT_CLASS_NAMED("KVAEntitlementsProduct")
@interface KVAEntitlementsProduct : NSObject
/// The singleton shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAProduct * _Nonnull shared;)
+ (KVAProduct * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Defines the parameters for the tracker product.
SWIFT_CLASS("_TtC19KochavaEntitlements28KVAEntitlementsProductParams")
@interface KVAEntitlementsProductParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAReceipt;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements30KVAEntitlementsReceiptReporter_")
@protocol KVAEntitlementsReceiptReporter
/// Reports a receipt.
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@end



/// A controller for working with entitlements receipts.
SWIFT_CLASS_NAMED("KVAEntitlementsReporting")
@interface KVAEntitlementsReporting : NSObject <KVAEntitlementsReceiptReporter, KVAEntitlementsReceiptReporterProvider>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end


/// A feature which provides for the internal observation of sessions.
SWIFT_CLASS_NAMED("KVAEntitlementsSessions")
@interface KVAEntitlementsSessions : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;
@class NSData;

/// An App Store receipt.
SWIFT_CLASS_NAMED("KVAReceipt")
@interface KVAReceipt : NSObject
/// A method which reports the current receipt.
+ (void)report;
/// A method which reports a receipt, along with an associated transaction’s details.
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithPriceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
/// \param reporter An instance which conforms to protocol KVAEntitlementsReceiptReporterProvider.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString reporter:(id <KVAEntitlementsReceiptReporterProvider> _Nullable)reporter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef KOCHAVAENTITLEMENTS_SWIFT_H
#define KOCHAVAENTITLEMENTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="KochavaEntitlements",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@protocol KVAEntitlementsReceiptReporter;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements38KVAEntitlementsReceiptReporterProvider_")
@protocol KVAEntitlementsReceiptReporterProvider
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end

@class NSString;
@class KVAContext;
@class KVAEntitlementsConfig;
@class KVAEntitlementsGeneral;
@class KVANetworking;
@class KVAEntitlementsReporting;

/// The class KVAEntitlements provides an interface between a host application and Kochava’s Entitlements servers.
SWIFT_CLASS_NAMED("KVAEntitlements")
@interface KVAEntitlements : NSObject <KVAEntitlementsReceiptReporterProvider>
/// A shared instance, for convenience.
/// This is the preferred way of using an entitlements instance.  To complete the integration you must call func <code>registerIdentity(withNameString:valueString:)</code> followed by func <code>start()</code>.  You may alternatively use a constructor to create your own entitlements.  The shared instance simplifies your implementation as you do not need to store an entitlements instance somewhere in a public location in your own code.
/// By default this instance will use the default storage location equivalent to calling <code>init(storageIdString:)</code> with storageIdString nil.  If you wish to specify an alternative storage location, see var <code>sharedStorageIdString</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nonnull shared;)
+ (KVAEntitlements * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// A shared instance, for convenience— optional.
/// See var <code>shared</code>.  This variable will be nil prior to the shared instance being defaulted.  This may be used to optionally invalidate any existing shared instance without causing it to first be defaulted in the process.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAEntitlements * _Nullable shared_optional;)
+ (KVAEntitlements * _Nullable)shared_optional SWIFT_WARN_UNUSED_RESULT;
/// The shared instance, an ambiguated form of the var <code>shared</code> which conforms to protocol KVASharedPropertyProvider.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) id _Nonnull sharedInstance;)
+ (id _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements()
/// }
///
/// \endcode
- (nonnull instancetype)init;
/// Create a entitlements.
/// You rarely create instances of class KVAEntitlements.  Instead, you start the provided shared instance using one of the start instance methods.  See static var <code>shared</code>.
/// <h2>Example</h2>
/// \code
/// class MyClass
/// {
///     let entitlements = KVAEntitlements(storageIdString: "alternate")
/// }
///
/// \endcode\param storageIdString An optional storage identifier.  The storage identifier should be left unset (nil) unless you have a reason to not use the default storage space.  See default constructor KVAEntitlements().
///
- (nonnull instancetype)initWithStorageIdString:(NSString * _Nullable)storageIdString OBJC_DESIGNATED_INITIALIZER;
/// Configure the instance with an object.
/// This is the same method which is used to configure the instance when the <code>config</code> response is returned from Kochava’s servers.  It can also be called from the host to change the defaults of various parameters (or else override them).  The structure of the object you provide has the same capability as that which the server may return.  Additionally you can wrap the parameters you provide in special objects with special keys <code>$default$</code>, <code>$default.append$</code>, <code>$override$</code>, or <code>$override.append$</code>, to indicate how these options are treated relative to the server’s options.
/// | Special Key | Treatment  |
/// — | —
/// $default$ |  Elements within this object will serve as a default for any options of the same name when not specified by the server.  The use of this option will replace any previous use of <code>$default$</code> or <code>$default.append$</code>.
/// $default.append$ |  Elements within this object will append to any previously established <code>$default$</code>.  You may use this without using <code>$default$</code> first, allowing you to specify multiple defaults over the course of multiple configuration calls.  The use of this option is generally considered preferred relative to the others.  That is because as a default it still allows for the server to specify overrides, and as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// $override$ |  Elements within this object will override any options of the same name specified by the server.  Use this option when you do not want to allow the server to specify overrides.  The use of this option will replace any previous use of <code>$override$</code> or <code>$override.append$</code>.
/// $override.append$ |  Elements within this object will append to any previously established <code>$override$</code>.  You may use this without using <code>$override$</code> first, allowing you to specify multiple overrides over the course of multiple configuration calls.  The use of this option is generally preferred to <code>$override$</code>.  That is because as an append it will respect any other previous configuration calls which you may have made at other times and places.
/// The following example will deny the collection of two datapoints, the idfa and idfv.  Ordinarily the best way to do this is through the Kochava dashboard, where these can be controlled within multiple version(s) of an app already in production.  However, if at build time you wanted to explicitly override server-side control, such that these two items effectively always appear in the deny datapoints list, the following code would do so:
/// <h2>Example</h2>
/// \code
/// // entitlementsConfigureObject
/// let entitlementsConfigureObject =
/// [
///     "$override.append$":
///     [
///         "privacy":
///         [
///             "deny_datapoints":
///             [
///                 "idfa",
///                 "idfv"
///             ]
///         ]
///     ]
/// ]
///
/// // KVAEntitlements
/// KVAEntitlements.shared.configure(with: entitlementsConfigureObject, context: .host)
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
/// KVAEntitlements.shared.start()
///
/// \endcode\param object An object from which to configure the instance.  This is most commonly a JSON object.
///
/// \param context The context from which the object was provided.  In rare cases this may have some bearing on the proper interpretation of what was provided.
///
- (void)configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Configure the instance with an object.
/// This function is equivalent to func configure(with:context) however this does not first dispatch to the globalSerial queue.  It is the protocol conformance of KVAConfigureWithProtocol.  You should not use this function directly unless you have a specific need to not perform the preferred dispatch.
- (void)kva_configureWith:(id _Nullable)object context:(KVAContext * _Nullable)context;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
/// Start the entitlements instance.
/// An identity must be registered prior to making this call.  To do this, instead see func <code>registerIdentity(withNameString:valueString:)</code>.  This method is called by those two methods, and provides public conformance to protocol KVAStartable.  This method can be used to start an instance of a entitlements which was created from decoded JSON.
- (void)start;
/// Return a description of the instance.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
/// Invalidate the instance.
/// When using this method with the shared instance, you are guaranteed to be re-defaulted a new instance the next time it is referenced, and you may immediately move forward to re-configure and start it.
- (void)invalidate;
/// Invalidate the instance.
/// See func <code>invalidate()</code>
- (void)invalidateWithAsyncBool:(BOOL)asyncBool printLogMessageBool:(BOOL)printLogMessageBool;
/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
@property (nonatomic, readonly, strong) KVAEntitlementsConfig * _Nonnull config;
/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
@property (nonatomic, readonly, strong) KVAEntitlementsGeneral * _Nonnull general;
/// A feature which provides networking support.
/// The networking instance manages the exchange of data between the client and various server(s), along with the associated tasks, network transactions, adapters, and instructions.  See class KVANetworking in module KochavaCore.
@property (nonatomic, readonly, strong) KVANetworking * _Nonnull networking;
/// A feature which is responsible for the collection of datapoints.
@property (nonatomic, readonly, strong) KVAEntitlementsReporting * _Nonnull reporting;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
/// A string used as a  storage identifier for the shared instance.
/// This is used to further qualify where in persistent storage the information for this instance is stored.  This property should not be used except in very specific circumstances.  Please contact your client success representative if you are interested in using this.  You would set this value to a short unique string consisting of regular alphanumeric characters.
/// Following deployment with a given storage identifer this should never be changed except to represent an entirely new integration.
/// If used, it is imperative that this value be consistently set prior to accessing the shared instance for the first time.  You must make accommodations to set this as early as possible, where it would be prior to any access to var <code>shared</code> throughout all of your code.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable sharedStorageIdString;)
+ (NSString * _Nullable)sharedStorageIdString SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedStorageIdString:(NSString * _Nullable)sharedStorageIdString;
/// A boolean indicating whether or not the instance has been started.
@property (nonatomic, readonly) BOOL startedBool;
@end


/// A feature which is responsible for controlling and updating the configuration of the entitlements instance.
/// This feature interfaces with Kochava’s servers to provide a server-based configuration.
SWIFT_CLASS_NAMED("KVAEntitlementsConfig")
@interface KVAEntitlementsConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which is responsible for the collection of datapoints.
/// <h1>Thread Safety</h1>
/// The underlying APIs being used to collect datapoints fall under various classifications of thread safety.  If an API is not thread safe then it must be collected on the main thread, otherwise it may be collected on the caller’s thread.  Anything which must be collected on the main thread must be viewed as asynchronous, along with those APIs which are themselves inherently asynchronous;  however, all other APIs may be viewed as synchronous.  In every case these thread safety classifications apply to the internal implementation stategies of the associated adapters, but the adapters themselves exist in part to create wrappers which have their own API(s) which are themselves uniform and universally thread safe.
/// Apple’s documentation on thread safety can be found here:
/// https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html
/// <h2>Internal Implementation Strategy Classifications</h2>
/// | Class | Safe | Notes |
/// — | — | —
/// Bundle | Yes | Apple’s documentation classifies Bundle under “Thread-Safe Classes and Functions”.
/// Locale | Yes* | Locale thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing is taken to be thread safe.
/// ProcessInfo | Yes | ProcessInfo is said to be thread-safe as of macOS 10.7 and later.
/// UIDevice | Yes* | UIDevice thread safety is undocumented by Apple at the time of this writing, but their broader documentation on thread safety says, “Immutable objects are generally thread-safe. Once you create them, you can safely pass these objects to and from threads.”  Because none of the properties which are being accessed are taken to be mutable, generally speaking, what we are doing may be thread safe.  However, Apple’s docs also say, “For the most part, UIKit classes should be used only from an application’s main thread. This is particularly true for classes derived from UIResponder or that involve manipulating your application’s user interface in any way.”  UIDevice is part of UIKit, however it is not derived from UIResponder (but rather NSObject).  This method is taken to not be involved in manipulating the application’s user interface.   https://developer.apple.com/documentation/uikit
/// Special | Varies | This classification is used for special cases.  There should be additional documentation in reference(s) which talk about the case.
/// <em>Yes*</em> - Items with this designation are taken to be safe.  They lack some level of documentation and/or clarity where thread safety is concerned, but often generally have a track record of being safe.
SWIFT_CLASS_NAMED("KVAEntitlementsDatapoints")
@interface KVAEntitlementsDatapoints : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// A feature which encapsulates all of the general aspects of a entitlements not belonging to any other encapsulated features.
SWIFT_CLASS_NAMED("KVAEntitlementsGeneral")
@interface KVAEntitlementsGeneral : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Register an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.registerIdentity(
///     withNameString: "_SOME_NAME_",
///     valueString: "_SOME_VALUE_"
/// )
///
/// \endcode
- (void)registerIdentityWithNameString:(NSString * _Nonnull)nameString valueString:(NSString * _Nonnull)valueString;
/// Unregister an identity.
/// <h2>Example</h2>
/// \code
/// KVAEntitlements.shared.general.unregisterIdentity(withNameString: "_SOME_NAME_")
///
/// \endcode
- (void)unregisterIdentityWithNameString:(NSString * _Nonnull)nameString;
@end


/// A feature which is responsible for entitlements-specific logging activities.
/// You can set the KVALog.shared.level to control what level of log messages are printed, as well as configure various other options through module KochavaCore class KVALog.
SWIFT_CLASS_NAMED("KVAEntitlementsLogging")
@interface KVAEntitlementsLogging : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAProduct;

/// A class which defines the entitlements product.
/// A product in this context generally refers to the result of a build.
/// note:
/// This is currently overridden to be a subclass of NSObject rather than KVAProduct so that it can be represented in Objective-C.  If you use KVAProduct it will still build, but the automatic module registration will fail to locate the class.  You can see early evidence of the problem if you also make the shared property be of the class type, where the compiler will say that it cannot use @objc because it cannot be expressed in Objective-C.  This is apparently a problem that Swift has providing Objective-C compatibility to Swift classes which subclass other Swift classes across modules.  For example, KVACoreProduct does not have this problem, presumably because it’s in the same module as KVAProduct.  In order to convert this class to subclass KVAProduct, or to subsequently allow shared to be of the class’ type, a means of registering/loading the class as a Swift-only class would be required.  More importantly, however, we’d need to give up public Objective-C support.  Since that doesn’t seem possible, the only alternative would be that Apple fixes this issue and provides the necessary support, assuming that’s possible.
SWIFT_CLASS_NAMED("KVAEntitlementsProduct")
@interface KVAEntitlementsProduct : NSObject
/// The singleton shared instance.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) KVAProduct * _Nonnull shared;)
+ (KVAProduct * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Defines the parameters for the tracker product.
SWIFT_CLASS("_TtC19KochavaEntitlements28KVAEntitlementsProductParams")
@interface KVAEntitlementsProductParams : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class KVAReceipt;

SWIFT_PROTOCOL("_TtP19KochavaEntitlements30KVAEntitlementsReceiptReporter_")
@protocol KVAEntitlementsReceiptReporter
/// Reports a receipt.
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@end



/// A controller for working with entitlements receipts.
SWIFT_CLASS_NAMED("KVAEntitlementsReporting")
@interface KVAEntitlementsReporting : NSObject <KVAEntitlementsReceiptReporter, KVAEntitlementsReceiptReporterProvider>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)reportReceipt:(KVAReceipt * _Nonnull)receipt;
@property (nonatomic, readonly, strong) id <KVAEntitlementsReceiptReporter> _Nonnull receiptReporter;
@end


/// A feature which provides for the internal observation of sessions.
SWIFT_CLASS_NAMED("KVAEntitlementsSessions")
@interface KVAEntitlementsSessions : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDecimalNumber;
@class NSData;

/// An App Store receipt.
SWIFT_CLASS_NAMED("KVAReceipt")
@interface KVAReceipt : NSObject
/// A method which reports the current receipt.
+ (void)report;
/// A method which reports a receipt, along with an associated transaction’s details.
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithPriceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString;
/// A method which reports a receipt.
/// \param appStoreReceiptData App store receipt data.
///
/// \param priceDecimalNumber The price of an associated transaction.  Optional.
///
/// \param currencyString The currency code of an associated transaction.  Optional.
///
/// \param reporter An instance which conforms to protocol KVAEntitlementsReceiptReporterProvider.
///
+ (void)reportWithAppStoreReceiptData:(NSData * _Nullable)appStoreReceiptData priceDecimalNumber:(NSDecimalNumber * _Nullable)priceDecimalNumber currencyString:(NSString * _Nullable)currencyString reporter:(id <KVAEntitlementsReceiptReporterProvider> _Nullable)reporter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
